# Generated by Django 2.2.9 on 2024-12-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_django_price_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
