# Generated by Django 2.2.9 on 2024-12-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0110_auto_20191108_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimal_variant_price_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
