# Generated by Django 2.2.9 on 2025-01-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0111_auto_20241218_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_customize',
            field=models.BooleanField(default=False, verbose_name='Show in Customize Products'),
        ),
    ]
