# Generated by Django 2.2.9 on 2024-12-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_auto_20190814_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='current_balance_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='initial_balance_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
