# Generated by Django 2.2.9 on 2024-12-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_django_price_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='maximum_order_price_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='minimum_order_price_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='price_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
