# Generated by Django 2.2.9 on 2024-12-18 09:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_django_price_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='captured_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.0'), max_digits=12),
        ),
    ]
